"""added coach_name and winner

Revision ID: 9e9021e6ea15
Revises: a28603a6e5bc
Create Date: 2026-02-22 02:22:06.582331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9021e6ea15'
down_revision: Union[str, None] = 'a28603a6e5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('coach_name', sa.String(length=255), nullable=True, comment='Bosh murabbiy ismi'))
    op.add_column('matches', sa.Column('winner', sa.String(length=50), nullable=True, comment="G'olib: HOME_TEAM, AWAY_TEAM yoki DRAW"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'winner')
    op.drop_column('clubs', 'coach_name')
    # ### end Alembic commands ###
