"""Initial models: League, Club, Match, Standing

Revision ID: a28603a6e5bc
Revises: 
Create Date: 2026-02-19 01:03:57.430877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28603a6e5bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment='Football-Data.org ID'),
    sa.Column('name_en', sa.String(length=255), nullable=False, comment='Liga nomi (inglizcha)'),
    sa.Column('name_uz', sa.String(length=255), nullable=True, comment="Liga nomi (o'zbekcha)"),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Liga kodi (PL, BL1, SA ...)'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Mamlakat nomi'),
    sa.Column('emblem_url', sa.String(length=500), nullable=True, comment='Original emblem URL'),
    sa.Column('emblem_local', sa.String(length=500), nullable=True, comment="Lokal saqlangan emblem yo'li"),
    sa.Column('season_start', sa.Date(), nullable=True, comment='Mavsum boshlanish sanasi'),
    sa.Column('season_end', sa.Date(), nullable=True, comment='Mavsum tugash sanasi'),
    sa.Column('current_matchday', sa.Integer(), nullable=True, comment="Hozirgi o'yin kuni"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Liga faolmi?'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_leagues_external_id'), 'leagues', ['external_id'], unique=True)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment='Football-Data.org ID'),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False, comment='Klub nomi (inglizcha)'),
    sa.Column('name_uz', sa.String(length=255), nullable=True, comment="Klub nomi (o'zbekcha)"),
    sa.Column('short_name', sa.String(length=50), nullable=True, comment='Qisqa nomi'),
    sa.Column('tla', sa.String(length=5), nullable=True, comment='3-harfli qisqartma (MUN, ARS ...)'),
    sa.Column('crest_url', sa.String(length=500), nullable=True, comment='Original club crest URL'),
    sa.Column('crest_local', sa.String(length=500), nullable=True, comment="Lokal saqlangan crest yo'li"),
    sa.Column('founded', sa.Integer(), nullable=True, comment='Tashkil etilgan yili'),
    sa.Column('venue', sa.String(length=255), nullable=True, comment='Stadion nomi'),
    sa.Column('venue_image_local', sa.String(length=500), nullable=True, comment='Stadion rasmi (lokal)'),
    sa.Column('website', sa.String(length=500), nullable=True, comment='Rasmiy veb-sayt'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Klub manzili'),
    sa.Column('wiki_summary_en', sa.Text(), nullable=True, comment='Wikipedia qisqa tavsifi (EN)'),
    sa.Column('wiki_summary_uz', sa.Text(), nullable=True, comment='Wikipedia qisqa tavsifi (UZ)'),
    sa.Column('club_colors', sa.String(length=100), nullable=True, comment='Klub ranglari'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_external_id'), 'clubs', ['external_id'], unique=True)
    op.create_index(op.f('ix_clubs_league_id'), 'clubs', ['league_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False, comment='Football-Data.org ID'),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('matchday', sa.Integer(), nullable=True, comment="O'yin kuni raqami"),
    sa.Column('status', sa.String(length=20), nullable=False, comment="O'yin holati: SCHEDULED, TIMED, IN_PLAY, PAUSED, FINISHED, POSTPONED, CANCELLED"),
    sa.Column('utc_date', sa.DateTime(timezone=True), nullable=False, comment="O'yin sanasi (UTC)"),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True, comment='Uy jamoasi gollari'),
    sa.Column('away_score', sa.Integer(), nullable=True, comment='Mehmon jamoasi gollari'),
    sa.Column('home_score_ht', sa.Integer(), nullable=True, comment='Uy jamoasi gollari (1-taym)'),
    sa.Column('away_score_ht', sa.Integer(), nullable=True, comment='Mehmon jamoasi gollari (1-taym)'),
    sa.Column('stage', sa.String(length=50), nullable=True, comment='Bosqich: REGULAR_SEASON, GROUP_STAGE, ROUND_OF_16, QUARTER_FINALS, SEMI_FINALS, FINAL'),
    sa.Column('group_name', sa.String(length=20), nullable=True, comment='UCL guruh nomi: Group A, B, C ...'),
    sa.Column('referee', sa.String(length=255), nullable=True, comment='Bosh hakam ismi'),
    sa.Column('duration', sa.String(length=20), nullable=True, comment='Davomiylik: REGULAR, EXTRA_TIME, PENALTY_SHOOTOUT'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=True)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False, comment='Mavsum yili (2024/2025 -> 2024)'),
    sa.Column('matchday', sa.Integer(), nullable=True, comment="Hozirgi o'yin kuni"),
    sa.Column('position', sa.Integer(), nullable=False, comment="Jadvaldagi o'rni"),
    sa.Column('played', sa.Integer(), nullable=False, comment="O'ynalgan o'yinlar soni"),
    sa.Column('won', sa.Integer(), nullable=False, comment="G'alabalar"),
    sa.Column('draw', sa.Integer(), nullable=False, comment='Duranglar'),
    sa.Column('lost', sa.Integer(), nullable=False, comment="Mag'lubiyatlar"),
    sa.Column('goals_for', sa.Integer(), nullable=False, comment='Urilgan gollar'),
    sa.Column('goals_against', sa.Integer(), nullable=False, comment='Yeyilgan gollar'),
    sa.Column('goal_difference', sa.Integer(), nullable=False, comment='Gollar farqi'),
    sa.Column('points', sa.Integer(), nullable=False, comment='Ochkolar'),
    sa.Column('form', sa.String(length=50), nullable=True, comment='Oxirgi natijalar: W,W,D,L,W'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'club_id', 'season', name='uq_standing_league_club_season')
    )
    op.create_index(op.f('ix_standings_club_id'), 'standings', ['club_id'], unique=False)
    op.create_index(op.f('ix_standings_league_id'), 'standings', ['league_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standings_league_id'), table_name='standings')
    op.drop_index(op.f('ix_standings_club_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_clubs_league_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_external_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_leagues_external_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
